site_name: SERVIDOR
theme:
  name: cinder
  color_mode: dark
  header_layout:
    - nav
nav:
  - Inicio: index.md
  - Manuales de instalación:
      - Introducción: manuales/index.md
      - Entornos virtuales de Python: manuales/entornos.md
      - WRF: manuales/wrf.md
      - GeoClaw: manuales/geoclaw.md 
  - APIs: apis/apis.md
  - Github: git_github.md
extra_css:
  - css/extra.css
extra_javascript:
   - js/copy-button.js
